### ISSUE TITLE
RendezvousTimeoutError meet on minikube.

### ISSUE THREAD

**Issue by Antlera** [intelligent-machine-learning/dlrover#374]
I am testing dlrover on ``minikube`` based on ``kvm`` driver. 
##Step to reproduce:
- 1.Start a ``kvm driver based minikube``.
- 2.Follow dlrover/doc/deployment/controller.md(Tests passed on ``docker driver based minikube``) to start a dlrover controller and Submit a mnist train job.

Worker pods start normally but ``RendezvousTimeoutError`` raised.
## log from torch-mnist-edljob-worker-0 the same as worker-1
```
[2023-04-03 09:37:16,464] [INFO] [master_client.py:545:build_master_client] getting global master client
[2023-04-03 09:37:16,466] [INFO] [master_client.py:76:__init__] dlrover master addr is elasticjob-torch-mnist-dlrover-master:50001
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 844, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1025, in next_rendezvous
    self._op_executor.run(join_op, deadline)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 638, in run
    raise RendezvousTimeoutError()
torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError
```
## log from  elasticjob-torch-mnist-dlrover-master 
```
[2023-04-03 09:47:01,038] [INFO] [rdzv_service.py:83:set_state] Host  set states with participants = ['torch-mnist-edljob-worker-0', 'torch-mnist-edljob-worker-1']
[2023-04-03 09:47:01,038] [INFO] [rdzv_service.py:114:get_state] Host  get states with participants = ['torch-mnist-edljob-worker-0', 'torch-mnist-edljob-worker-1']
[2023-04-03 09:47:01,593] [INFO] [rdzv_service.py:114:get_state] Host  get states with participants = ['torch-mnist-edljob-worker-0', 'torch-mnist-edljob-worker-1']
... SAME [INFO]
[2023-04-03 09:47:15,663] [INFO] [rdzv_service.py:114:get_state] Host  get states with participants = ['torch-mnist-edljob-worker-0', 'torch-mnist-edljob-worker-1']
[2023-04-03 09:47:15,665] [INFO] [rdzv_service.py:83:set_state] Host  set states with participants = ['torch-mnist-edljob-worker-0', 'torch-mnist-edljob-worker-1']
[2023-04-03 09:47:15,665] [INFO] [rdzv_service.py:114:get_state] Host  get states with participants = ['torch-mnist-edljob-worker-0', 'torch-mnist-edljob-worker-1']
[2023-04-03 09:47:15,865] [INFO] [job_manager.py:400:_process_event] torch-mnist-edljob-worker-0 status change: Running to Failed, by evt_type MODIFIED reason Error
[2023-04-03 09:47:16,668] [INFO] [rdzv_service.py:114:get_state] Host  get states with participants = []
[2023-04-03 09:47:16,670] [INFO] [rdzv_service.py:83:set_state] Host  set states with participants = []
[2023-04-03 09:47:16,670] [INFO] [rdzv_service.py:114:get_state] Host  get states with participants = []
[2023-04-03 09:47:16,875] [INFO] [job_manager.py:400:_process_event] torch-mnist-edljob-worker-1 status change: Running to Failed, by evt_type MODIFIED reason Error
[2023-04-03 09:47:41,638] [ERROR] [master.py:150:run] All workers failed
[2023-04-03 09:47:41,638] [INFO] [master.py:202:stop] Job exit with the reason UnknownError
[2023-04-03 09:47:41,638] [INFO] [master.py:207:stop] Stopping master
[2023-04-03 09:47:41,638] [INFO] [master.py:208:stop] Stopping RPC server
[2023-04-03 09:47:41,639] [INFO] [master.py:210:stop] RPC server stopped
[2023-04-03 09:47:41,639] [INFO] [master.py:211:stop] Master stopped
```

# What should I do to debug this problem?

**Comment by Antlera** [comment]
> Which image dose the master use? You can view the image by `kubectl -n dlrover get pod {master-pod-name} | grep image`. If the image is `registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:test`, you can deployment the elasticjob controller to update the master image `registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:master`. https://github.com/intelligent-machine-learning/dlrover/blob/master/dlrover/go/operator/config/manifests/bases/deployment.yaml#L48
> 
> By the way. `registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:test` is the test image that may have bugs. We will update the `registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:master` after we complete testing the master branch.

Thks for your comment. I would try It out later.

**Comment by Antlera** [comment]
> 

Workers run properly now. Thank you for replying.
