### ISSUE TITLE
Error when request GPU resouces.

### ISSUE THREAD

**Issue by Antlera** [intelligent-machine-learning/dlrover#379]
Deploy the controller and submit the torch_mnist_master_backend_job.
## error log from pod `` ``
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/scheduler/kubernetes.py", line 94, in create_custom_resource
    self.api_instance.create_namespaced_custom_object(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 225, in create_namespaced_custom_object
    return self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 344, in create_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 276, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '6e6bcf0b-a7c1-4244-a2be-c9ba2bea1ff4', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '72b03a68-2dd4-4229-9f7a-63688b98fef4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '871bf699-e2a7-455b-97ef-206442a591cb', 'Date': 'Wed, 05 Apr 2023 02:34:07 GMT', 'Content-Length': '904'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ScalePlan.elastic.iml.github.io \"torch-mnist-scaleplan-0\" is invalid: spec.replicaResourceSpecs.worker.resource.gpu_type: Invalid value: \"nvidia.com/gpu\": spec.replicaResourceSpecs.worker.resource.gpu_type in body should match '^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$'","reason":"Invalid","details":{"name":"torch-mnist-scaleplan-0","group":"elastic.iml.github.io","kind":"ScalePlan","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"nvidia.com/gpu\": spec.replicaResourceSpecs.worker.resource.gpu_type in body should match '^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$'","field":"spec.replicaResourceSpecs.worker.resource.gpu_type"}]},"code":422}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/master/main.py", line 53, in <module>
    os._exit(main())
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/master/main.py", line 48, in main
    exit_code = run(args)
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/master/main.py", line 42, in run
    master.prepare()
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/master/master.py", line 121, in prepare
    self.job_manager.start()
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/master/node/job_manager.py", line 164, in start
    self._scaler.scale(plan)
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/master/scaler/elasticjob_scaler.py", line 183, in scale
    self._client.create_custom_resource(
  File "/usr/local/lib/python3.8/site-packages/dlrover/python/scheduler/kubernetes.py", line 102, in create_custom_resource
    logger.error(
Message: 'Exception when calling CustomObjectsApi->'
Arguments: ('create_namespaced_custom_object: (422)\nReason: Unprocessable Entity\nHTTP response headers: HTTPHeaderDict({\'Audit-Id\': \'6e6bcf0b-a7c1-4244-a2be-c9ba2bea1ff4\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flowschema-Uid\': \'72b03a68-2dd4-4229-9f7a-63688b98fef4\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'871bf699-e2a7-455b-97ef-206442a591cb\', \'Date\': \'Wed, 05 Apr 2023 02:34:07 GMT\', \'Content-Length\': \'904\'})\nHTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ScalePlan.elastic.iml.github.io \\"torch-mnist-scaleplan-0\\" is invalid: spec.replicaResourceSpecs.worker.resource.gpu_type: Invalid value: \\"nvidia.com/gpu\\": spec.replicaResourceSpecs.worker.resource.gpu_type in body should match \'^(\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))))?$\'","reason":"Invalid","details":{"name":"torch-mnist-scaleplan-0","group":"elastic.iml.github.io","kind":"ScalePlan","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \\"nvidia.com/gpu\\": spec.replicaResourceSpecs.worker.resource.gpu_type in body should match \'^(\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))))?$\'","field":"spec.replicaResourceSpecs.worker.resource.gpu_type"}]},"code":422}\n\n',)
[2023-04-05 02:34:07,875] [INFO] [speed_monitor.py:53:set_target_worker_num] The target number of worker : 1
[2023-04-05 02:34:07,876] [INFO] [job_manager.py:274:_monitor_nodes] Start to monitor nodes
[2023-04-05 02:34:07,876] [INFO] [job_manager.py:295:_monitor_scale_plan_crd] Start to monitor Scaler CRD
```
## kubectl describe pod elasticjob-torch-mnist-dlrover-master

```
Containers:
  main:
    Container ID:  containerd://483b56c8ee1bd2a063f143b22ae05667080c7e1e16c4f73ea80bfe0895fd2f35
    Image:         registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:master
    Image ID:      registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover@sha256:e4464d120a16993949ebe249cb6b750c16b825b3a92bb05511a5ce03b7938791
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      python -m dlrover.python.master.main --platform k8s --namespace dlrover --job_name torch-mnist --port 50001
    State:          Running
      Started:      Wed, 05 Apr 2023 10:34:02 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:                1
      ephemeral-storage:  2Gi
      memory:             2Gi
    Requests:
      cpu:                1
      ephemeral-storage:  2Gi
      memory:             2Gi
    Environment:          <none>

```

## reference to nvidia gpu pod example
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
```
## logs from gpu-pod
```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```
## kubectl describe pod gpu-pod
```
Containers:
  cuda-container:
    Container ID:   containerd://c05e8c915e871fa89372eddf6c1318462f2ae474b01d60b1e084c5bb0e77a5ee
    Image:          nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
    Image ID:       nvcr.io/nvidia/k8s/cuda-sample@sha256:4593078cdb8e786d35566faa2b84da1123acea42f0d4099e84e2af0448724af1
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 05 Apr 2023 00:56:26 +0800
      Finished:     Wed, 05 Apr 2023 00:56:26 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
```
so gpu resource is acessible for gpu-pod but invalid for  elasticjob-torch-mnist-dlrover-master.

**Comment by workingloong** [comment]
Thanks for your detail description and we have fixed it in PR #381 . After the PR is merged, we will update the image of master.
