### ISSUE TITLE
Warning about pytest.

### ISSUE THREAD

**Issue by Antlera** [intelligent-machine-learning/dlrover#506]
When running a test against the code in the master branch, a direct WARNING occurs.

```log
=============================== warnings summary ===============================
dlrover/python/tests/test_resource_optimizer.py::ResourceOptimizerTest::test_brain_optimizer
dlrover/python/tests/test_resource_optimizer.py::ResourceOptimizerTest::test_brain_optimizer
  /home/lan/toolkit/miniconda3/envs/dl_torch/lib/python3.8/site-packages/kubernetes/client/rest.py:44: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.
    return self.urllib3_response.getheaders()

dlrover/python/tests/test_resource_optimizer.py::ResourceOptimizerTest::test_brain_optimizer
  /home/lan/toolkit/miniconda3/envs/dl_torch/lib/python3.8/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread pod-creater
  
  Traceback (most recent call last):
    File "/home/lan/toolkit/miniconda3/envs/dl_torch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/home/lan/toolkit/miniconda3/envs/dl_torch/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/lan/CodeSpace/dlrover/dlrover/python/master/scaler/pod_scaler.py", line 310, in _periodic_create_pod
      pod = self._create_pod(
    File "/home/lan/CodeSpace/dlrover/dlrover/python/master/scaler/pod_scaler.py", line 352, in _create_pod
      worker_num = pod_stats[node.type]
  KeyError: 'worker'
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================= 98 passed, 3 warnings in 45.25s ========================
```

**Comment by workingloong** [comment]
I have fixed it. 
https://github.com/intelligent-machine-learning/dlrover/blob/master/dlrover/python/master/scaler/pod_scaler.py#L367
