### ISSUE TITLE
Fail to run the example of nanogpt.

### ISSUE THREAD

**Issue by workingloong** [intelligent-machine-learning/dlrover#533]
```
rank 0 is initialized local_rank = 0
Traceback (most recent call last):
  File "model_zoo/pytorch/nanogpt/train.py", line 379, in <module>
    train()
  File "model_zoo/pytorch/nanogpt/train.py", line 178, in train
    assert gradient_accumulation_steps % world_size == 0
AssertionError
```

**Comment by Antlera** [comment]
Closed as fixed by #535.
