### ISSUE TITLE
Localmaster stopped before workers finished their task.

### ISSUE THREAD

**Issue by Antlera** [intelligent-machine-learning/dlrover#627]
**Problem Description:** 
Master stop too early, even when there are still worker running.

**Steps to Reproduce:**
Run this script
```bash
# run master
python -m dlrover.python.master.main --platform pyk8s --namespace dlrover --job_name torch-nanogpt-debug --port 50001 > master.log 2>&1 &

export DLROVER_MASTER_ADDR=127.0.0.1:50001
# run worker
dlrover-run --nnodes=1 --nproc_per_node=2 --max_restarts=1 dlrover/model_zoo/pytorch/nanogpt/train.py \
    --data_dir ./data/nanogpt \
    --gradient_accumulation_steps 2 --max_iters 10000 --device 'cuda' > wokers.log 2>&1
```

**Expected Behavior:**
Master stop after all the workers finish their tasks and processes exit.

**Actual Behavior:**
Master stop early then the workers can not connect to the master.

`Master log`

```log
<mark>[2023-08-17 14:25:20,825] [INFO] [args.py:65:print_args] port = 50001</mark>
[2023-08-17 14:25:20,825] [INFO] [args.py:65:print_args] job_name = torch-nanogpt-debug
[2023-08-17 14:25:20,825] [INFO] [args.py:65:print_args] namespace = dlrover
[2023-08-17 14:25:20,825] [INFO] [args.py:65:print_args] platform = pyk8s
[2023-08-17 14:25:20,825] [INFO] [factory.py:34:new_job_args] New pyk8s JobParameters
[2023-08-17 14:25:21,139] [INFO] [kubernetes.py:107:__init__] Load the kube config file.
[2023-08-17 14:25:21,163] [INFO] [kubernetes.py:373:initilize] Job args = {'platform': 'pyk8s', 'namespace': 'dlrover', 'job_name': 'torch-nanogpt-debug', 'node_args': {'dlrover-master': <dlrover.python.scheduler.job.NodeArgs object at 0x7fa792d5fee0>, 'worker': <dlrover.python.scheduler.job.NodeArgs object at 0x7fa792d5fd00>}, 'enable_dynamic_sharding': True, 'enable_elastic_scheduling': True, 'distribution_strategy': 'AllreduceStrategy', 'job_uuid': '13052665-61d5-4ec8-889b-5af2501390fb', 'user': 'lan', 'cluster': '', 'optimize_mode': 'single-job', 'resource_limits': <dlrover.python.scheduler.job.ResourceLimits object at 0x7fa795deb790>, 'relaunch_always': False}
[2023-08-17 14:25:21,163] [INFO] [main.py:39:run] Job args : {"cluster": "", "distribution_strategy": "AllreduceStrategy", "enable_dynamic_sharding": true, "enable_elastic_scheduling": true, "job_name": "torch-nanogpt-debug", "job_uuid": "13052665-61d5-4ec8-889b-5af2501390fb", "namespace": "dlrover", "node_args": {"dlrover-master": {"auto_scale": true, "critical_nodes": "", "group_resource": {"count": 0, "node_resource": {"cpu": 0.0, "gpu_num": 0, "gpu_type": null, "image": "", "kwargs": {}, "memory": 0, "priority": ""}}, "restart_count": 3, "restart_timeout": 0}, "worker": {"auto_scale": true, "critical_nodes": "", "group_resource": {"count": 2, "node_resource": {"cpu": 4.0, "gpu_num": 1, "gpu_type": "nvidia.com/gpu", "image": "", "kwargs": {}, "memory": 16384, "priority": ""}}, "restart_count": 3, "restart_timeout": 0}}, "optimize_mode": "single-job", "platform": "pyk8s", "relaunch_always": false, "resource_limits": {"cpu": 100.0, "gpu_num": 4, "memory": {}}, "user": "lan"}
[2023-08-17 14:25:21,179] [WARNING] [client.py:276:build_brain_client] The GRPC service of brain is not available.
[2023-08-17 14:25:21,179] [WARNING] [client.py:88:__init__] Cannot initialize brain channel
[2023-08-17 14:25:21,188] [INFO] [global_context.py:161:print_config] DLRover global context = {'train_speed_record_num': 50, 'seconds_to_autoscale_worker': 90, 'step_to_adjust_worker': 200, 'optimize_worker_cpu_threshold': 20, 'seconds_for_stable_worker_count': 60, 'seconds_interval_to_optimize': 300, 'factor_to_cut_pending_cpu': 2, 'factor_to_cut_pending_mem': 2, 'seconds_to_wait_pending_pod': 900, 'seconds_huge_training_threshold': 1800, 'sample_count_to_adjust_worker': 5, 'seconds_interval_to_change_ps': 3600, 'seconds_to_wait_failed_ps': 600, 'auto_worker_enabled': True, 'auto_ps_enabled': False, 'is_tfv1_ps': False, 'master_port': 50001, 'relaunch_always': False}
[2023-08-17 14:25:21,188] [INFO] [factory.py:20:new_elastic_job] New pyk8s ElasticJob
[2023-08-17 14:25:21,188] [INFO] [factory.py:19:new_node_watcher] New pyk8s NodeWatcher
[2023-08-17 14:25:21,189] [INFO] [factory.py:21:new_job_scaler] New pyk8s JobScaler
[2023-08-17 14:25:21,198] [INFO] [dist_job_manager.py:136:__init__] New job optimizer : <class 'dlrover.python.master.resource.job.AllreduceJobResourceOptimizer'>
[2023-08-17 14:25:21,198] [INFO] [factory.py:33:new_scale_plan_watcher] New pyk8s NodeWatcher
[2023-08-17 14:25:21,198] [INFO] [reporter.py:90:new_stats_reporter] New local stats reporter.
[2023-08-17 14:25:21,199] [INFO] [servicer.py:489:create_master_service] Creating master service
[2023-08-17 14:25:21,204] [INFO] [servicer.py:514:create_master_service] The port of the master server is: 50001
[2023-08-17 14:25:21,204] [INFO] [dist_master.py:131:prepare] Starting master RPC server
[2023-08-17 14:25:21,205] [INFO] [dist_master.py:133:prepare] Master RPC server started
[2023-08-17 14:25:21,206] [INFO] [job.py:144:init_job_node_meta] after initiating job node meta job_nodes are {'dlrover-master': {}, 'worker': {0: name:torch-nanogpt-debug-edljob-worker-0;rank_index:0;type:worker;status:Initial;addr:torch-nanogpt-debug-edljob-worker-0.dlrover.svc:3333;is_released:False;priroity:, 1: name:torch-nanogpt-debug-edljob-worker-1;rank_index:1;type:worker;status:Initial;addr:torch-nanogpt-debug-edljob-worker-1.dlrover.svc:3333;is_released:False;priroity:}}
[2023-08-17 14:25:21,206] [INFO] [training_node.py:54:set_critical_node] Critical workers = {}
[2023-08-17 14:25:21,206] [INFO] [dist_job_manager.py:288:_init_job_auto_scaler] Create job autoscaler: <class 'dlrover.python.master.node.job_auto_scaler.AllreduceTrainingAutoScaler'>
[2023-08-17 14:25:21,230] [INFO] [pod_scaler.py:133:scale] Scale the job by plan {"launch_nodes": [], "node_group_resources": {"dlrover-master": {"count": 0, "node_resource": {"cpu": 0.0, "gpu_num": 0, "gpu_type": null, "image": "", "kwargs": {}, "memory": 0, "priority": ""}}, "worker": {"count": 2, "node_resource": {"cpu": 4.0, "gpu_num": 1, "gpu_type": "nvidia.com/gpu", "image": "", "kwargs": {}, "memory": 16384, "priority": ""}}}, "ps_addrs": [], "remove_nodes": []}
[2023-08-17 14:25:21,230] [INFO] [speed_monitor.py:60:set_target_worker_num] The target number of worker : 2
[2023-08-17 14:25:21,230] [INFO] [dist_job_manager.py:293:_monitor_nodes] Start to monitor nodes
[2023-08-17 14:25:23,212] [INFO] [rdzv_manager.py:100:update_rdzv_params] elastic-training manager updates rdzv params: min_nodes=1, max_nodes=1, waiting_timeout=60, node_unit=1
[2023-08-17 14:25:23,212] [INFO] [rdzv_manager.py:100:update_rdzv_params] network-check manager updates rdzv params: min_nodes=1, max_nodes=1, waiting_timeout=60, node_unit=1
[2023-08-17 14:25:23,214] [INFO] [rdzv_manager.py:165:join_rendezvous] elastic-training waiting nodes: {0: 2}
[2023-08-17 14:25:23,215] [INFO] [rdzv_manager.py:133:_check_rdzv_completed] Completed 0 round rendezvous of elastic-training is {0: 2}
[2023-08-17 14:25:51,260] [WARNING] [dist_master.py:185:run] All workers exited but there also are unfinished tasks
[2023-08-17 14:25:51,261] [INFO] [dist_master.py:234:stop] Job exit with the reason Completed
[2023-08-17 14:25:51,261] [INFO] [dist_master.py:239:stop] Stopping master
[2023-08-17 14:25:51,261] [INFO] [dist_master.py:240:stop] Stopping RPC server
[2023-08-17 14:25:51,266] [INFO] [dist_master.py:242:stop] RPC server stopped
[2023-08-17 14:25:51,266] [INFO] [dist_master.py:243:stop] Master stopped
```

`worker log`
```log
[2023-08-17 14:25:23,123] [INFO] [master_client.py:473:build_master_client] Build master client with addr 127.0.0.1:50001.
[2023-08-17 14:25:23,184] [INFO] [master_client.py:75:__init__] dlrover master addr is 127.0.0.1:50001
[2023-08-17 14:25:23,207] [INFO] [elastic_run.py:140:_check_dlrover_master_available] Check the master grpc servicer on 127.0.0.1
[2023-08-17 14:25:23,207] [INFO] [elastic_run.py:142:_check_dlrover_master_available] Check the master grpc servicer on 50001
[2023-08-17 14:25:23,207] [INFO] [elastic_run.py:148:_check_dlrover_master_available] DLRover job master starts!
[2023-08-17 14:25:23,207] [INFO] [master_client.py:473:build_master_client] Build master client with addr 127.0.0.1:50001.
[2023-08-17 14:25:23,208] [INFO] [master_client.py:75:__init__] dlrover master addr is 127.0.0.1:50001
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-08-17 14:25:23,210] [INFO] [training.py:480:launch_agent] Starting elastic_operator with launch configs:
  entrypoint       : dlrover/model_zoo/pytorch/nanogpt/train.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 2
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900, 'node_unit': 1}
  max_restarts     : 1
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

[2023-08-17 14:25:23,213] [INFO] [training.py:371:_invoke_run] [default] starting workers for entrypoint: python
[2023-08-17 14:25:23,214] [INFO] [training.py:139:next_rendezvous] The node node_name attempts to join the next round of the rendezvous 'elastic-training' with timeout 600.
[2023-08-17 14:25:23,215] [INFO] [training.py:167:next_rendezvous] The node has joined round 0 of the elastic-training rendezvous as rank 0 in a world of size 1.
[2023-08-17 14:25:23,219] [INFO] [training.py:280:_rendezvous] [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.1.1
  master_port=38499
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

rank 0 is initialized local_rank = 0
rank 1 is initialized local_rank = 1
tokens per iteration will be: 3,072
found vocab_size = 65 (inside ./data/nanogpt/meta.pkl)
found vocab_size = 65 (inside ./data/nanogpt/meta.pkl)
Initializing a new model from scratch
Initializing a new model from scratch
number of parameters: 10.65M
number of parameters: 10.65M
Running basic DDP example on local rank 1.
Running basic DDP example on local rank 0.
Model device cuda:1
creating optimizer...<generator object Module.parameters at 0x7fe4b6fcae40>
Model device cuda:0
creating optimizer...<generator object Module.parameters at 0x7f4d76b0be40>
iter 0: loss 4.2418, time 1346.72ms, mfu -100.00%, cuda memory 0.322G, lr 6.00e-04, total time 1.35siter 0: loss 4.2582, time 1346.82ms, mfu -100.00%, cuda memory 0.322G, lr 6.00e-04, total time 1.35s

iter 1: loss 3.4346, time 87.78ms, mfu -100.00%, cuda memory 0.357G, lr 6.00e-04, total time 1.43siter 1: loss 3.4465, time 87.78ms, mfu -100.00%, cuda memory 0.357G, lr 6.00e-04, total time 1.43s

iter 2: loss 3.8898, time 29.40ms, mfu -100.00%, cuda memory 0.358G, lr 6.00e-04, total time 1.46s
iter 2: loss 3.8853, time 29.57ms, mfu -100.00%, cuda memory 0.358G, lr 6.00e-04, total time 1.46s
...
iter 2297: loss 1.3357, time 34.09ms, mfu 0.96%, cuda memory 0.358G, lr 6.00e-04, total time 78.87s
iter 2297: loss 1.2521, time 34.11ms, mfu 0.96%, cuda memory 0.358G, lr 6.00e-04, total time 78.90s
--- Logging error ---
Traceback (most recent call last):
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/torch/training.py", line 449, in _membership_changed
    num_nodes_waiting = rdzv_handler.num_nodes_waiting()
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/torch/training.py", line 190, in num_nodes_waiting
    return self._client.num_nodes_waiting(self._name)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/master_client.py", line 46, in wrapper
    raise execption
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/master_client.py", line 34, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/master_client.py", line 333, in num_nodes_waiting
    response = self._stub.num_nodes_waiting(request)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: Connection refused {created_time:"2023-08-17T14:26:38.317702278+00:00", grpc_status:14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/bin/dlrover-run", line 8, in <module>
    sys.exit(main())
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/trainer/torch/elastic_run.py", line 199, in main
    run(args)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/trainer/torch/elastic_run.py", line 188, in run
    elastic_launch(
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/trainer/torch/elastic_run.py", line 99, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/torch/training.py", line 545, in launch_agent
    result = agent.run()
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/torch/training.py", line 421, in _invoke_run
    if self._membership_changed(role, rdzv_handler):
  File "/home/lan/DevelopmentTools/miniconda3/envs/dl_nanogpt/lib/python3.8/site-packages/dlrover/python/elastic_agent/torch/training.py", line 451, in _membership_changed
    logger.warning("Fail to call num_node_waiting.", e)
Message: 'Fail to call num_node_waiting.'
Arguments: (<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: Connection refused {created_time:"2023-08-17T14:26:38.317702278+00:00", grpc_status:14}"
>,)
[2023-08-17 14:26:48,330] [WARNING] [master_client.py:36:wrapper] Retry 0 to MasterClient.num_nodes_waiting with failure
iter 2298: loss 1.3242, time 34.07ms, mfu 0.96%, cuda memory 0.358G, lr 6.00e-04, total time 78.94s
iter 2298: loss 1.3497, time 34.27ms, mfu 0.97%, cuda memory 0.358G, lr 6.00e-04, total time 78.90s
```

**Note:**
local master stop at `[2023-08-17 14:25:51,266]`
worker log warning at `[2023-08-17 14:26:48,330]`

**Comment by Antlera** [comment]
Closed as now we run a different style command with `dlrover-run --standalone ...`
